// Operating cash flow (indirect method) engine — the standard FASB ASC 230 reconciliation from
// net income to cash generated by core operations: add back non-cash charges (depreciation,
// amortization), then adjust for the change in each working-capital line. A rising asset
// (receivables, inventory) ties up cash and is SUBTRACTED; a rising liability (payables) frees up
// cash and is ADDED. This is the same formula a company's own cash flow statement uses, just
// applied to whatever numbers you enter.

export interface OperatingCashFlowInput {
  netIncome: number;
  depreciation: number;
  amortization: number;
  /** Change in accounts receivable over the period. Positive = receivables grew (uses cash). */
  changeInReceivables: number;
  /** Change in inventory over the period. Positive = inventory grew (uses cash). */
  changeInInventory: number;
  /** Change in accounts payable over the period. Positive = payables grew (frees cash). */
  changeInPayables: number;
  /** Any other non-cash adjustments or working-capital changes, net (+ adds cash, - uses cash). */
  otherAdjustments: number;
}

export interface OperatingCashFlowResult {
  operatingCashFlow: number | null;
  nonCashAddBacks: number | null;
  workingCapitalChange: number | null;
}

const EMPTY: OperatingCashFlowResult = { operatingCashFlow: null, nonCashAddBacks: null, workingCapitalChange: null };

export function computeOperatingCashFlow(input: OperatingCashFlowInput): OperatingCashFlowResult {
  const netIncome = input.netIncome ?? 0;
  const depreciation = Math.max(0, input.depreciation ?? 0);
  const amortization = Math.max(0, input.amortization ?? 0);
  const changeInReceivables = input.changeInReceivables ?? 0;
  const changeInInventory = input.changeInInventory ?? 0;
  const changeInPayables = input.changeInPayables ?? 0;
  const otherAdjustments = input.otherAdjustments ?? 0;

  if (netIncome === 0 && depreciation === 0 && amortization === 0 && changeInReceivables === 0
      && changeInInventory === 0 && changeInPayables === 0 && otherAdjustments === 0) {
    return EMPTY;
  }

  const nonCashAddBacks = round2(depreciation + amortization);
  const workingCapitalChange = round2(-changeInReceivables - changeInInventory + changeInPayables + otherAdjustments);
  const operatingCashFlow = round2(netIncome + nonCashAddBacks + workingCapitalChange);

  return { operatingCashFlow, nonCashAddBacks, workingCapitalChange };
}

function round2(n: number): number { return Math.round(n * 100) / 100; }
