exec(open('mk_head.py').read())
I_MORT=["/mortgage/ (mortgage calculator hub)","/mortgage/closing-cost-calculator/ (calculator)","/mortgage/home-affordability-calculator/ (calculator)","/guides/first-time-home-buyer-guide/ (existing guide)","/guides/current-mortgage-rates-guide/ (existing guide)","/compare/bridge-loan-vs-heloc/ (comparison)","/compare/heloc-vs-home-equity-loan/ (comparison)","/heloc-calculator/ (calculator)"]
row("how-to-buy-and-sell-a-house-at-the-same-time","buy and sell a house at the same time",
 "sell and buy a house at once, buy before selling, home sale contingency, bridge loan, rent back",
 'informational, "how do I sell my house and buy another without being stuck"',
 "How do you buy and sell a house at the same time without owning two homes or being homeless?",
 "Pick one of four structures before you list: make a sale-contingent offer, sell first and rent back or rent short term, buy first using home equity or a bridge loan, or line up a closing on the same day; the right one depends on how much cash you can carry for two housing payments and how competitive your market is.",
 'section 1 "Four Ways to Sequence a Sale and a Purchase" (the four structures and when each fits), before any background',
 [
 "Hypothetical worked example (engine-computed): carrying two mortgages. A $400,000 30-year fixed mortgage at 6.5% has a principal-and-interest payment of $2,528.27 a month. If the old home's payment is $2,528.27 and the new home's payment is $3,000, carrying both for 3 months costs $16,584.81 before taxes, insurance and utilities.",
 "Under IRC Section 121, a homeowner can exclude up to $250,000 of gain on the sale of a main home ($500,000 for most married couples filing jointly) if they owned and used it as their main home for at least 2 of the 5 years before the sale. Source: IRS Topic 701 and Publication 523.",
 "A home sale contingency makes an offer conditional on selling your current home; sellers in a competitive market often treat it as a weaker offer. A rent-back (post-closing occupancy) agreement lets a seller stay in the sold home for an agreed period after closing. Terms are negotiated and vary by state and contract; the page must say so and not state a standard length.",
 "A bridge loan is short-term financing secured by the current home, used to cover a down payment before the sale closes; rates, fees and terms vary by lender and are not published as a standard figure. The page must tell the reader to get a written quote. A HELOC on the current home is the common alternative; HELOCs generally must be opened before the home is listed because lenders can be reluctant to open one on a home that is for sale (reader to verify with the lender).",
 "Lenders count both housing payments in the debt-to-income ratio unless the old mortgage will be paid off at closing with documented sale proceeds; the page must say to ask the lender how it will treat the old mortgage. No specific DTI limit may be stated as a rule.",
 "Closing costs, moving costs, and overlapping insurance and utility bills are real costs of a double move; the page may not state a percentage of price.",
 ],
 ["https://www.irs.gov/taxtopics/tc701","https://www.irs.gov/publications/p523"],
 I_MORT,
 ["Four ways to sequence a sale and a purchase, with the decision rule for each (answers the reader question).",
  "Sell first: the rent-back and short-term-rental route, what it costs in moves and storage, what to negotiate.",
  "Buy first: carrying two payments with the $2,528.27 and $3,000 worked example; the cash cushion test.",
  "Bridge loan vs HELOC on the home you are selling, and why to line financing up before listing.",
  "Contingent offers: how sellers read them and what makes one stronger.",
  "How the lender counts the old mortgage in your debt-to-income ratio.",
  "The home sale gain exclusion: the 2-of-5-year test and $250,000/$500,000 amounts.",
  "A dated checklist from 90 days before listing to closing day.",
  "Who this is not for and what would change our answer (e.g., sellers with little equity, or a market where homes sell above ask in days)."],
 ["Can you buy a house before selling your current one?","Should I sell first or buy first?","What is a bridge loan and is it worth it?","Do I owe tax when I sell my house and buy another?","What is a rent-back agreement?"],
 "How to Buy and Sell a House at the Same Time",
 "Ways to time a sale and purchase; buying first; selling first; contingent offers; bridge loans; HELOC; rent-back; costs; tips",
 "NerdWallet", ANCH)

row("how-to-fund-a-trust","how to fund a trust",
 "funding a living trust, transfer assets to trust, retitle assets to trust, trust funding checklist, pour-over will",
 'informational, "I made a trust, now how do I put things in it"',
 "How do you fund a trust, and which assets get retitled versus left alone?",
 "Funding a trust means changing legal ownership or beneficiary designations so the trust, not you personally, controls each asset: retitle real estate by deed, bank and brokerage accounts by new account title, and handle retirement accounts through beneficiary designations rather than retitling, because moving a 401(k) or IRA into a trust can trigger a taxable distribution.",
 'section 1 "What Funding a Trust Means for Each Asset Type" (asset-by-asset table in prose), before background',
 [
 "A trust only controls assets that are titled in its name or that name it as beneficiary. An unfunded trust generally leaves assets subject to probate, which is the usual reason people create a revocable living trust. The page must present this as the general rule and say state rules differ.",
 "Real estate is moved into a trust by recording a new deed; recording requirements, transfer-tax exemptions and title-insurance effects vary by state and county, so the page must tell the reader to check with the county recorder and title insurer, with no specific fee stated.",
 "Bank and brokerage accounts are retitled in the trust's name with the institution's own forms; some institutions instead allow a payable-on-death (POD) or transfer-on-death (TOD) designation, which is simpler but is not the same as trust funding.",
 "Retirement accounts (401(k), IRA, 403(b)) are not retitled to a living trust during life because that would generally be treated as a distribution; the usual approach is to name beneficiaries on the account, sometimes including a trust for a specific reason. The page must tell the reader to get tax advice before naming a trust as an IRA beneficiary.",
 "Life insurance and annuities are funded by changing the beneficiary or owner on the policy; vehicles depend on state titling rules, and many people leave low-value vehicles outside the trust. Tangible personal property is typically moved with an assignment document. A pour-over will is a backstop that directs assets left outside the trust into it at death, but those assets still go through probate. Stated generally; states differ.",
 "Business interests: LLC membership or stock may need operating-agreement or shareholder consent to assign; the page must say to read the governing documents first.",
 "Hypothetical worked example: a household has a home, two bank accounts, a brokerage account, two IRAs and a car. Retitle the home, the two bank accounts and the brokerage account; keep the IRAs outside and name beneficiaries; leave the car out. No dollar figures may be used.",
 ],
 [],
 ["/guides/is-a-living-trust-worth-it/ (existing guide)","/compare/living-trust-vs-will/ (comparison)","/compare/probate-vs-trust/ (comparison)","/compare/revocable-vs-irrevocable-trust/ (comparison)","/guides/trust-tax-rates-explained/ (existing guide)","/roundup/best-living-trust-services/ (roundup)"],
 ["What funding a trust means, asset by asset (answers the reader question).",
  "Real estate: the deed and what varies by state.",
  "Bank and brokerage accounts: retitle vs POD/TOD.",
  "Retirement accounts and life insurance: beneficiary designations, not retitling.",
  "Vehicles, personal property and business interests.",
  "The pour-over will as a backstop and what it does not avoid.",
  "The worked household example: what goes in, what stays out.",
  "A step-by-step funding checklist and how to keep it current as you open new accounts.",
  "Who this is not for and what would change our answer (e.g., small estates, community-property states)."],
 ["What happens if you do not fund a trust?","Do you put your house in a living trust?","Can you put a 401(k) or IRA in a trust?","How long does it take to fund a trust?","Do I need a lawyer to fund a trust?"],
 "How to Fund a Trust: Step-By-Step Guide",
 "What funding means; which assets to transfer; real estate; accounts; retirement accounts; insurance; vehicles; business interests; mistakes",
 "SmartAsset", ANCH)

row("taxes-on-options-trading","taxes on options trading",
 "how options are taxed, options capital gains, section 1256 contracts, wash sale options, short-term vs long-term options",
 'informational, "how are my option trades taxed"',
 "How are options taxed in the US, and what changes when an option is exercised, expires or is sold?",
 "Gains and losses on most equity options are capital gains, short-term if held one year or less and long-term if held longer than one year, but exercise, assignment and expiration each change the result: an exercised call adds the premium to the stock's cost basis, while a short option's premium is a short-term gain when it expires or is closed.",
 'section 1 "How Each Option Outcome Is Taxed" (sell, expire, exercise, assigned), before background',
 [
 "A long option that is sold at a profit or loss produces a capital gain or loss; the holding period is measured from purchase to sale, one year or less is short-term, more than one year is long-term. Source: IRS Publication 550.",
 "A long option that expires worthless is treated as a capital loss on the expiration date. Source: IRS Publication 550.",
 "If you exercise a call you bought, the premium paid is added to the basis of the stock acquired and no gain or loss is recognized on the option at exercise. If you exercise a put you bought, the premium reduces the amount realized on the stock sale. Source: IRS Publication 550.",
 "For a short option (one you wrote), the premium received is not taxed when received; it is reported as a short-term capital gain when the option expires, is closed out, or is exercised and the premium is folded into the stock's sale or basis calculation. Source: IRS Publication 550.",
 "Section 1256 contracts, which include nonequity options such as broad-based index options, are taxed 60% as long-term and 40% as short-term capital gain regardless of holding period, are marked to market at year end, and are reported on Form 6781. Equity options on single stocks and most ETFs are not Section 1256 contracts. Source: IRS Publication 550 and Form 6781 instructions.",
 "The wash sale rule disallows a loss if you buy substantially identical stock or securities (including options) within 30 days before or after the sale at a loss; the disallowed loss is added to the basis of the new position. Source: IRS Publication 550.",
 "Hypothetical worked example: a $10,000 gain on a Section 1256 index option is taxed as $6,000 long-term and $4,000 short-term. A 22% ordinary bracket and a 15% long-term rate give 0.22 x 4,000 + 0.15 x 6,000 = $880 + $900 = $1,780, or 17.8% blended. The same $10,000 on a single-stock option held 6 months at 22% is $2,200. Rates are illustrative only; the reader must verify current brackets.",
 "Brokers report option proceeds on Form 1099-B; the taxpayer reports sales on Form 8949 and Schedule D. Qualified covered calls and some spreads have special rules; the page must tell the reader to read Publication 550 or consult a tax professional for straddles and qualified covered calls.",
 ],
 ["https://www.irs.gov/publications/p550","https://www.irs.gov/taxtopics/tc409"],
 ["/compare/ordinary-income-vs-capital-gains-tax/ (comparison)","/guides/capital-gains-tax-for-seniors/ (existing guide)","/compare/brokerage-vs-ira/ (comparison)","/portfolio/ (portfolio calculator hub)","/guides/tax-deductions-checklist/ (existing guide)"],
 ["How each option outcome is taxed: sell, expire, exercise, assigned (answers the reader question).",
  "Short-term vs long-term holding periods for options.",
  "Buying a call or put and exercising it: the basis adjustments.",
  "Writing options: when the premium is taxed.",
  "Section 1256 index options and the 60/40 split, with the $10,000 worked example.",
  "The wash sale rule as it applies to options.",
  "Reporting: Form 1099-B, Form 8949, Schedule D, Form 6781.",
  "A record-keeping checklist for active traders.",
  "Who this is not for and what would change our answer (e.g., straddles, qualified covered calls, trader tax status)."],
 ["Are options taxed as ordinary income or capital gains?","How are expired options taxed?","What are Section 1256 contracts?","Does the wash sale rule apply to options?","Do I owe tax when I exercise an option?"],
 "How Options Are Taxed",
 "Short-term vs long-term; selling; expiring; exercising; short options; Section 1256; wash sales; reporting",
 "SmartAsset", ANCH)

row("what-do-brokers-charge-to-trade","trading fees brokers charge",
 "brokerage fees, stock trading commissions, options contract fees, hidden brokerage costs, bid-ask spread",
 'informational, "what does it actually cost to trade stocks"',
 "What do brokers actually charge to trade, and which costs are not on the commission line?",
 "Most large US online brokers charge $0 commission on online stock and ETF trades, so the real cost sits elsewhere: options contract fees, mutual fund transaction fees, account and transfer fees, the bid-ask spread, and the expense ratio of any fund you buy.",
 'section 1 "Where the Cost of a Trade Actually Sits" (the list of cost layers), before background',
 [
 "Most large US online brokers now advertise $0 commissions for online stock and ETF trades; options contracts, mutual funds outside a no-transaction-fee list, broker-assisted trades, foreign stocks and OTC securities are often charged. The page must not state any specific broker's fee or any specific per-contract amount; it must tell the reader to read the broker's current fee schedule.",
 "The bid-ask spread is the gap between the best price a buyer will pay and the best a seller will accept; a market order buys at the ask and sells at the bid, so a wider spread costs the investor more even at $0 commission.",
 "Hypothetical worked example (illustrative numbers): a stock quoted $50.00 bid and $50.10 ask. Buying 100 shares at the ask costs $5,010 and selling immediately at the bid returns $5,000, a $10 round-trip cost, or 0.2% of the purchase.",
 "Payment for order flow is the practice of brokers receiving payments from market makers for routing customer orders to them; it is one way brokers earn money on commission-free trades, and it is disclosed in broker order-routing reports. The page must present this as a tradeoff to understand, not a claim about any broker.",
 "A limit order lets you set the maximum buy price or minimum sell price, which controls spread cost but may not fill. Source: general order-type definition.",
 "Regulatory fees on sales: the SEC Section 31 fee and the FINRA Trading Activity Fee are small fees charged on stock sales and are usually passed through by the broker; rates change, so the page must tell the reader to check sec.gov and finra.org for current rates and must not state a rate.",
 "Fund costs: an ETF's or mutual fund's expense ratio is deducted from fund assets every year and is separate from any trade commission. Hypothetical: a 0.50% expense ratio on $10,000 is $50 a year; a 0.05% ratio is $5 a year.",
 "Other possible charges: account transfer-out (ACATS) fees, inactivity or maintenance fees, paper statement fees, margin interest, wire fees. Policies vary by broker; the page must say to check the fee schedule.",
 ],
 ["https://www.sec.gov/","https://www.finra.org/"],
 ["/portfolio/ (portfolio calculator hub)","/compare/brokerage-vs-ira/ (comparison)","/compare/401k-vs-brokerage-account/ (comparison)","/roundup/best-robo-advisors/ (roundup)","/guides/financial-advisor-worth-it/ (existing guide)"],
 ["Where the cost of a trade actually sits: commission, options fees, spread, fund expense ratio, account fees (answers the reader question).",
  "Commissions: what $0 covers and what it does not.",
  "Options and mutual fund fees: what to look for in a fee schedule.",
  "The bid-ask spread with the $50.00 / $50.10 worked example, and limit orders.",
  "Payment for order flow as a tradeoff.",
  "Regulatory pass-through fees on sales.",
  "Expense ratios with the $10,000 example.",
  "Account-level fees: transfer-out, inactivity, margin interest.",
  "A checklist to compare two brokers' fee schedules.",
  "Who this is not for and what would change our answer (e.g., frequent options traders vs buy-and-hold index investors)."],
 ["Are there fees to trade stocks?","What is the bid-ask spread?","What is payment for order flow?","Do ETFs have trading fees?","What is the cheapest way to buy stocks?"],
 "Trading Fees: What Do Brokers Charge to Trade?",
 "Commissions; options fees; spreads; order flow; fund fees; account fees; how to choose",
 "SmartAsset", ANCH)

row("who-overpays-on-mortgages","who overpays on mortgages",
 "mortgage overpay, mortgage rate shopping, compare mortgage lenders, mortgage loan estimate, how many mortgage quotes",
 'informational, "am I getting a good mortgage rate or overpaying"',
 "Who overpays on a mortgage, and how much does a small rate difference cost over the loan?",
 "Borrowers overpay mostly by taking the first offer they receive: on a $400,000 30-year loan, a 0.25 percentage point higher rate (6.50% instead of 6.25%) costs $65.40 more a month and about $23,545 more over 30 years, which is why comparing Loan Estimates from several lenders is the highest-value step.",
 'section 1 "What a Quarter-Point Costs" (worked example), before background',
 [
 "Hypothetical worked example (engine-computed): $400,000, 30-year fixed. At 6.50% the principal-and-interest payment is $2,528.27; at 6.25% it is $2,462.87. The difference is $65.40 a month, which is about $23,545 over 360 payments if the loan is held to term.",
 "A lender must provide a Loan Estimate within 3 business days of receiving a mortgage application; it is a standard 3-page form that makes offers comparable. Source: CFPB.",
 "Credit scoring models generally treat multiple mortgage inquiries within a short window as a single inquiry for scoring, so shopping around does not stack hard-inquiry penalties. The window length depends on the scoring model (commonly cited as 14 to 45 days); the page must say to confirm with the lender and must not state one number as a rule. Source: CFPB.",
 "Compare the interest rate, the APR, points and lender credits, and the closing costs on page 2 of the Loan Estimate; a lower rate that comes with more points is not necessarily cheaper unless the borrower keeps the loan long enough to recoup them. The page may show the breakeven method: extra upfront cost divided by monthly savings.",
 "Hypothetical breakeven: paying $4,000 in points to lower the payment by $65.40 a month breaks even after about 61 months ($4,000 / $65.40 = 61.16).",
 "Mortgage rates and the credit score tier a borrower falls into affect pricing; the page may not state any score cutoffs or a current market rate, and must point to the existing current mortgage rates guide.",
 "Common ways to overpay (stated as patterns, with no statistics): accepting one lender's quote, ignoring lender fees and points, rolling closing costs into the loan without comparing, keeping private mortgage insurance after it can be removed, and never reviewing a refinance when rates drop meaningfully. Source: CFPB consumer guidance (reader to verify).",
 ],
 ["https://www.consumerfinance.gov/owning-a-home/"],
 ["/mortgage/ (mortgage calculator hub)","/mortgage/closing-cost-calculator/ (calculator)","/mortgage/home-affordability-calculator/ (calculator)","/guides/current-mortgage-rates-guide/ (existing guide)","/guides/first-time-home-buyer-guide/ (existing guide)","/guides/mortgage-early-payoff-tax-implications/ (existing guide)"],
 ["What a quarter-point costs: the $400,000 worked example (answers the reader question).",
  "The ways borrowers overpay: one quote, points and fees, rolled-in closing costs, PMI left in place, refinances never reviewed.",
  "How to compare Loan Estimates line by line.",
  "Rate shopping and your credit score.",
  "Points and the breakeven method with the $4,000 example.",
  "A step-by-step plan for getting and comparing quotes the week you apply.",
  "Who this is not for and what would change our answer (e.g., short holding period, tiny loan balance, or a borrower with limited lender choices)."],
 ["How many mortgage lenders should I compare?","Does shopping for a mortgage hurt my credit?","How much does 0.25% matter on a mortgage?","What is a Loan Estimate?","Are mortgage points worth it?"],
 "These Borrowers Are Most Likely to Overpay Their Mortgage",
 "Who overpays; why; how to avoid overpaying",
 "Bankrate", ANCH)
