import { useMemo, useState } from "react";
import { computeOperatingCashFlow, type OperatingCashFlowInput } from "../lib/operating-cash-flow";
import { fmtUSD } from "../lib/format";

// Operating cash flow island (indirect method, FASB ASC 230). Built for the business-financing
// vertical: a business shopping for a loan or line of credit needs to know its own operating cash
// flow before it can judge whether a lender's cash-flow covenant is realistic. Standalone, no
// host coupling (mirrors InterestPerDayCalculator).

interface Props {
  initialData?: Partial<OperatingCashFlowInput>;
  heading?: string;
  subheading?: string;
}

const DEFAULTS: OperatingCashFlowInput = {
  netIncome: 120000,
  depreciation: 25000,
  amortization: 5000,
  changeInReceivables: 15000,
  changeInInventory: 10000,
  changeInPayables: 8000,
  otherAdjustments: 0,
};

export default function OperatingCashFlowCalculator({ initialData, heading, subheading }: Props) {
  const [input, setInput] = useState<OperatingCashFlowInput>({ ...DEFAULTS, ...initialData });
  const result = useMemo(() => computeOperatingCashFlow(input), [input]);
  const set = (patch: Partial<OperatingCashFlowInput>) => setInput((s) => ({ ...s, ...patch }));

  const isPositive = (result.operatingCashFlow ?? 0) >= 0;

  return (
    <div style={S.wrap}>
      {(heading || subheading) && (
        <div style={S.head}>
          {heading && <div style={S.heading}>{heading}</div>}
          {subheading && <div style={S.subheading}>{subheading}</div>}
        </div>
      )}

      <div style={S.grid}>
        <div style={S.inputs}>
          <Field label="Net income">
            <MoneyInput value={input.netIncome} onChange={(v) => set({ netIncome: v })} allowNegative />
          </Field>
          <Field label="Depreciation">
            <MoneyInput value={input.depreciation} onChange={(v) => set({ depreciation: v })} />
          </Field>
          <Field label="Amortization">
            <MoneyInput value={input.amortization} onChange={(v) => set({ amortization: v })} />
          </Field>
          <Field label="Change in accounts receivable (+ = grew)">
            <MoneyInput value={input.changeInReceivables} onChange={(v) => set({ changeInReceivables: v })} allowNegative />
          </Field>
          <Field label="Change in inventory (+ = grew)">
            <MoneyInput value={input.changeInInventory} onChange={(v) => set({ changeInInventory: v })} allowNegative />
          </Field>
          <Field label="Change in accounts payable (+ = grew)">
            <MoneyInput value={input.changeInPayables} onChange={(v) => set({ changeInPayables: v })} allowNegative />
          </Field>
          <Field label="Other adjustments, net (+ adds cash)">
            <MoneyInput value={input.otherAdjustments} onChange={(v) => set({ otherAdjustments: v })} allowNegative />
          </Field>
          <p style={S.hint}>
            A rising receivable or inventory balance ties up cash (subtracted); a rising payable balance frees up cash (added) — the standard indirect-method adjustment.
          </p>
        </div>

        <div style={S.results}>
          <div style={S.bigStat}>
            <span style={S.bigLabel}>Operating cash flow</span>
            <span style={S.bigValue}>{fmtUSD(result.operatingCashFlow)}</span>
            <span style={S.bigSub}>cash generated by core operations this period</span>
          </div>

          <div style={S.statRow}>
            <Stat label="Non-cash add-backs" value={fmtUSD(result.nonCashAddBacks)} />
            <Stat label="Working-capital change" value={fmtUSD(result.workingCapitalChange)} />
          </div>

          <div style={{ ...S.aprBox, ...(isPositive ? S.aprOk : S.aprWarn) }}>
            <span style={S.aprLabel}>What this means</span>
            <span style={S.aprNote}>
              {isPositive
                ? "Positive operating cash flow means core operations generated more cash than they consumed this period, before any financing or investing activity."
                : "Negative operating cash flow means core operations consumed more cash than they generated this period — a lender evaluating a cash-flow covenant will treat this as a red flag regardless of reported net income."}
            </span>
          </div>

          <div style={S.disclaimer}>
            Estimate only. Uses the indirect method (net income plus non-cash charges, adjusted
            for working-capital changes) — the same reconciliation a company's own cash flow
            statement uses. Does not include investing or financing cash flows.
          </div>
        </div>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label style={S.field}>
      <span style={S.label}>{label}</span>
      {children}
    </label>
  );
}
function MoneyInput({ value, onChange, allowNegative }: { value: number; onChange: (v: number) => void; allowNegative?: boolean }) {
  return (
    <div style={S.suffixWrap}>
      <span style={S.prefix}>$</span>
      <input
        style={{ ...S.input, paddingLeft: 22 }}
        inputMode={allowNegative ? "text" : "numeric"}
        value={value === 0 ? "" : value.toLocaleString("en-US")}
        placeholder="0"
        onChange={(e) => {
          const raw = e.target.value.replace(/[^0-9.\-]/g, "");
          if (raw === "" || raw === "-") { onChange(0); return; }
          const n = Number(raw);
          onChange(allowNegative ? n : Math.max(0, n));
        }}
      />
    </div>
  );
}
function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div style={S.stat}>
      <span style={S.statLabel}>{label}</span>
      <span style={S.statValue}>{value}</span>
    </div>
  );
}

const PRIMARY = "#0E7C66";
const S: Record<string, React.CSSProperties> = {
  wrap: { fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif", color: "#1A1A1A" },
  head: { marginBottom: 16 },
  heading: { fontSize: "1.2rem", fontWeight: 700 },
  subheading: { fontSize: "0.95rem", color: "#555", marginTop: 2 },
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: 24 },
  inputs: { display: "flex", flexDirection: "column", gap: 12 },
  field: { display: "flex", flexDirection: "column", gap: 5 },
  label: { fontSize: "0.82rem", fontWeight: 600, color: "#444" },
  input: { width: "100%", padding: "10px 12px", fontSize: "1rem", border: "1px solid #D0DAD6", borderRadius: 8, background: "#fff", boxSizing: "border-box", color: "#1A1A1A" },
  suffixWrap: { position: "relative", display: "flex", alignItems: "center" },
  prefix: { position: "absolute", left: 11, color: "#888", fontSize: "0.95rem", pointerEvents: "none" },
  hint: { fontSize: "0.82rem", color: "#666", lineHeight: 1.5, margin: "2px 0 0" },
  results: { background: "linear-gradient(180deg,#F4FAF8 0%,#FFFFFF 100%)", border: "1px solid #D8EEE6", borderRadius: 14, padding: 18, display: "flex", flexDirection: "column", gap: 12, alignSelf: "start" },
  bigStat: { display: "flex", flexDirection: "column", gap: 2, paddingBottom: 8, borderBottom: "1px solid #E6F0EC" },
  bigLabel: { fontSize: "0.8rem", fontWeight: 600, color: "#2A6A58", textTransform: "uppercase", letterSpacing: "0.04em" },
  bigValue: { fontSize: "2rem", fontWeight: 800, color: PRIMARY, letterSpacing: "-0.02em" },
  bigSub: { fontSize: "0.8rem", color: "#777", marginTop: 2 },
  statRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  stat: { display: "flex", flexDirection: "column", gap: 1 },
  statLabel: { fontSize: "0.78rem", color: "#666" },
  statValue: { fontSize: "1.15rem", fontWeight: 700, fontVariantNumeric: "tabular-nums" },
  aprBox: { borderRadius: 10, padding: "12px 14px", display: "flex", flexDirection: "column", gap: 1, border: "1px solid #E0EBE7", background: "#fff" },
  aprOk: { background: "#EAF7F1", borderColor: "#BFE6D7" },
  aprWarn: { background: "#FBF4E4", borderColor: "#F0DEB4" },
  aprLabel: { fontSize: "0.78rem", fontWeight: 600, color: "#666", textTransform: "uppercase", letterSpacing: "0.03em" },
  aprNote: { fontSize: "0.8rem", color: "#777" },
  disclaimer: { fontSize: "0.76rem", color: "#7a8783", lineHeight: 1.5, marginTop: 2 },
};
