import type { SpokeEntry } from "./types";
import { IRS_SE_TAX, IRS_SCHED_C, IRS_ES } from "./spokes-self-employed";

// Business-structure spokes (2026-09-05). Powered by src/lib/s-corp-tax.ts through the "s-corp-tax"
// island. These sit under their own pillar rather than under /self-employment-tax/ because entity
// choice is a structure decision, not a tax calculation — and because the cluster has its own head
// term ("s corp tax calculator", 1,300/mo KD 12) with unusually soft difficulty beneath it.

const IRS_SCORP_COMP = {
  label: "IRS — S corporation compensation and medical insurance issues",
  url: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues",
};
const IRS_2553 = {
  label: "IRS — Instructions for Form 2553",
  url: "https://www.irs.gov/instructions/i2553",
};
const IRS_SCORP = {
  label: "IRS — S corporations",
  url: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporations",
};

export const S_CORP_SPOKES: SpokeEntry[] = [
  {
    calculator: "s-corp-tax",
    slug: "s-corp-reasonable-salary-calculator",
    updated: "2026-09-05",
    title: "S Corp Reasonable Salary Calculator (2026)",
    metaDescription:
      "An S corp reasonable salary calculator that shows what each salary level costs you. There is no 60/40 rule — see what the IRS actually requires.",
    targetKeyword: "s corp reasonable salary calculator",
    estimatedVolume: 320,
    estimatedKD: 3,
    h1: "S Corp Reasonable Salary Calculator",
    introText:
      "Your S corporation salary is the number the IRS scrutinises, and the one that decides whether the election saves you anything. Set it too low and you invite reclassification; set it too high and the election stops paying for itself.\n\nThe calculator shows both sides. On $150,000 of profit with a $75,000 salary, the election nets $5,131 a year. Raise the salary to a very conservative level and that saving disappears — at $90,000 of profit with a $70,000 salary, an election costs $1,530.",
    howItWorks:
      "There is no formula, and that is the single most important thing to understand before using any calculator that offers one. The IRS states that S corporations must pay reasonable compensation to a shareholder-employee for services provided before non-wage distributions are made, and it publishes no safe harbor and no percentage.\n\nThe factors it actually weighs are: training and experience; duties and responsibilities; time and effort devoted to the business; dividend history; payments to non-shareholder employees; the timing and manner of paying bonuses; what comparable businesses pay for similar services; compensation agreements; and the use of a formula to determine compensation.\n\nUnderlying all of them is a single question — where do the corporation's gross receipts come from? If they are generated by the shareholder's own services, that value should be treated as wages subject to employment taxes. If they come from non-shareholder employees or from capital and equipment, the payments may reasonably be non-wage distributions. This is the test that decides most cases, and it is why a solo consultant whose revenue is entirely their own billable time has far less room than an owner whose business runs on staff and assets.\n\nThe \"60/40 rule\" and the \"2% rule\" that circulate widely online are not IRS positions. Neither appears in IRS guidance, and neither will defend a salary that fails the facts-and-circumstances test. A percentage is a starting sanity check at best.\n\nThe practical way to arrive at a defensible figure is to price the job rather than split the profit: find what someone would be paid to do the work you actually do, using compensation surveys or job listings for your role, market, and hours. If you work part-time in the business, prorate. Document the reasoning at the time, because the reasonable-compensation question is answered years later, under examination, on the evidence you kept.\n\nThen run the number. The calculator above shows what each salary level does to the total: the payroll tax you avoid on the distribution, the QBI deduction you forfeit because wages are not qualified business income, and the payroll costs. A salary that is more defensible is also more expensive, and seeing both figures together is the only way to judge whether the election is worth making at all. The [S corp tax calculator](/s-corp-tax/) covers the full election decision.",
    commonMistakes: [
      "Using the 60/40 rule as though it were IRS guidance. It is not in any IRS publication, and it will not defend a salary that fails the facts-and-circumstances test.",
      "Setting the salary to whatever makes the tax saving look best. The IRS can reclassify distributions as wages, with back payroll tax, interest, and penalties — and the reclassification lands on the years already filed.",
      "Ignoring where the revenue comes from. A solo consultant billing their own time has far less room to take distributions than an owner whose revenue is produced by staff and equipment.",
      "Forgetting that a higher salary shrinks the QBI deduction. Wages are not qualified business income, so a conservative salary costs you twice — more payroll tax and a smaller §199A deduction.",
      "Not documenting the reasoning at the time. Reasonable compensation is examined years later, and a figure you can explain with contemporaneous evidence is worth far more than one you reconstruct.",
    ],
    workedExample:
      "A consultant with $150,000 of business profit pays herself $75,000 — half of profit — after checking what employed consultants in her market earn for comparable work. The election avoids $9,719 of payroll tax on the $68,063 distribution, but forfeits $11,048 of QBI deduction and costs $1,200 in payroll service and the extra return. The net saving is $5,131 a year. Now take a business where the owner's own billable time generates essentially all the revenue, so a defensible salary is much closer to profit: at $90,000 of profit and a $70,000 salary, the payroll tax avoided falls to $2,007 while the forfeited QBI deduction is $10,819. The election costs $1,530 a year rather than saving anything.",
    faqs: [
      {
        question: "What is a reasonable salary for an S corp owner?",
        answer:
          "Whatever it would cost to hire someone to do the work you actually do, judged on your duties, hours, training, and what comparable businesses pay. The IRS publishes no safe harbor and no percentage. Its controlling test is the source of the corporation's gross receipts: revenue generated by your own services should be paid as wages rather than taken as distributions.",
      },
      {
        question: "Is the 60/40 rule real?",
        answer:
          "No. Neither the 60/40 split nor the 2% rule appears in IRS guidance, and neither will support a salary that fails the facts-and-circumstances test. They circulate because a percentage is easier to repeat than a judgement. Use market compensation data for your actual role and hours instead, and keep the evidence you relied on.",
      },
      {
        question: "What happens if my S corp salary is too low?",
        answer:
          "The IRS can reclassify distributions as wages, which brings back payroll tax on the reclassified amount plus interest and penalties, applied to years you have already filed. Courts have repeatedly upheld this authority. The exposure is not limited to the tax saved, which is why an aggressive salary is a poor trade against a saving of a few thousand dollars a year.",
      },
      {
        question: "Does a higher salary always cost me money?",
        answer:
          "It costs you twice, which is why the trade-off matters. More salary means more payroll tax, and because wages are not qualified business income, it also means a smaller QBI deduction. That is why a conservative salary can flip an election from saving money to costing it — at $90,000 of profit with a $70,000 salary, the election costs $1,530 a year.",
      },
      {
        question: "Can I pay myself nothing and take only distributions?",
        answer:
          "No, not if you provide services to the corporation. The IRS requires reasonable compensation for those services before non-wage distributions are made, and a zero salary with substantial distributions is the clearest case for reclassification. If the business genuinely produced no profit, no distribution is being made either, which is a different situation from taking money out without paying wages.",
      },
    ],
    sources: [IRS_SCORP_COMP, IRS_SCORP, IRS_SE_TAX],
    toolHeading: "Reasonable salary calculator",
    toolSubheading: "Change the salary to see what each level costs",
    preset: {
      netProfit: 150000,
      reasonableSalary: 75000,
      filingStatus: "single",
      payrollCost: 1200,
      note: "There is no IRS safe harbor for this number. Price the job — what would you pay someone to do the work you actually do? — rather than splitting profit by a percentage.",
    },
    relatedSlugs: ["llc-vs-s-corp-tax-calculator"],
  },

  {
    calculator: "s-corp-tax",
    slug: "llc-vs-s-corp-tax-calculator",
    updated: "2026-09-05",
    title: "LLC vs S Corp Tax Calculator (2026)",
    metaDescription:
      "Compare LLC and S corp taxes side by side for your own profit. Includes the QBI deduction and payroll costs that decide whether an election is worth it.",
    targetKeyword: "llc vs s corp tax calculator",
    estimatedVolume: 210,
    estimatedKD: 4,
    h1: "LLC vs S Corp Tax Calculator",
    introText:
      "A default LLC and an LLC taxed as an S corporation are the same legal entity paying tax two different ways. The calculator runs both on your own profit and reports the difference after payroll costs and the QBI deduction.\n\nAt $120,000 of profit with a $60,000 salary, the default LLC pays $28,462 in federal tax and the S-corp route costs $24,291 all-in — a difference of $4,171 a year.",
    howItWorks:
      "The comparison is narrower than it first appears, because the two options are not different entities. An LLC is a legal structure; S-corp is a tax election that an LLC can make while remaining an LLC. Liability protection, your operating agreement, and state registration do not change. What changes is how profit is taxed.\n\nUnder default taxation, a single-member LLC is a disregarded entity: profit goes on Schedule C, and all of it is subject to self-employment tax at 15.3% of 92.35%. The arrangement is simple, needs no payroll, and costs nothing extra to run.\n\nUnder an S-corp election, the LLC files Form 1120-S, pays you a W-2 salary, and passes the remaining profit to you on a K-1. Payroll tax applies only to the salary. In exchange you take on real payroll obligations and a separate business return.\n\nThe calculator prices all of it, including the two offsets that decide most cases. The first is the QBI deduction: wages are not qualified business income, so salary shrinks the §199A base. At $120,000 of profit the forfeited deduction is $8,242 against $7,775 of payroll tax avoided — the election still wins once income tax is worked through, but the gross figure alone would have overstated it badly. The second is payroll cost, which recurs annually whether or not the business has a good year.\n\nThere is also a non-tax difference worth weighing. Paying yourself a salary reduces the earnings on which Social Security credits accrue, which matters at the margins for future benefits, and it makes personal borrowing simpler because a W-2 is easier for lenders to underwrite than a Schedule C.\n\nWhere the answer lands depends more on the salary than on the profit. Hold salary at half of profit and the election clears $1,000 a year of net benefit at around $35,000 of profit. Hold it at 60% and the threshold moves to roughly $52,000. For a business whose revenue is entirely the owner's own billable time — where a defensible salary is close to all of the profit — the election may never pay. Our [LLC vs S corp comparison](/compare/llc-vs-s-corp/) covers the non-tax differences, and the [reasonable salary calculator](/s-corp-tax/s-corp-reasonable-salary-calculator/) covers the number this all turns on.",
    commonMistakes: [
      "Treating LLC and S-corp as competing entity types. S-corp is a tax election an LLC can make; the legal entity and its liability protection do not change.",
      "Comparing only payroll tax. The QBI deduction moves in the opposite direction, and at moderate profit the forfeited deduction can exceed the payroll tax avoided.",
      "Leaving payroll costs out of the comparison. A payroll service plus a separate Form 1120-S recurs every year, in bad years as well as good.",
      "Assuming state treatment matches federal. Several states tax S corporations directly or impose franchise fees, which can erase a modest federal saving entirely.",
      "Forgetting the effect on Social Security. A lower salary means lower earnings on record, which reduces the benefit base for later retirement.",
    ],
    workedExample:
      "A designer's LLC earns $120,000 of profit. Taxed by default, she pays $16,955 of self-employment tax and $11,506 of federal income tax after a $19,084 QBI deduction — $28,462 in total. Electing S-corp treatment with a $60,000 salary, she pays $9,180 of payroll tax across both halves, and her QBI deduction falls to $10,842 because only the $54,210 distribution counts as qualified business income, which raises her income tax to $13,911. Adding $1,200 of payroll costs brings the S-corp route to $24,291. The election saves $4,171 — real money, but 46% less than the $7,775 of payroll tax avoided would have suggested.",
    faqs: [
      {
        question: "Is an LLC or S corp better for taxes?",
        answer:
          "Neither is inherently better; it depends on your profit and the salary you can defend. A default LLC pays self-employment tax on all profit but keeps the full QBI deduction and costs nothing to run. An S-corp election shelters the distribution from payroll tax but shrinks the QBI deduction and adds payroll costs. At $120,000 of profit with a $60,000 salary the election saves about $4,171 a year; at $90,000 with a $70,000 salary it costs $1,530.",
      },
      {
        question: "Can an LLC be taxed as an S corp?",
        answer:
          "Yes, and that is the usual route for a one-person business. S-corp is a tax election rather than an entity type, so an LLC files Form 2553 and continues to exist as an LLC for legal purposes. You keep the simpler LLC formalities and change only how profit is taxed — the liability protection, operating agreement, and state registration are unaffected.",
      },
      {
        question: "How much profit do I need before an S corp is worth it?",
        answer:
          "Around $35,000 of profit if you hold salary at half of profit, and about $52,000 at a more conservative 60% salary — measured as the point where the net saving clears $1,000 a year. Below that, payroll costs and the forfeited QBI deduction outweigh the payroll tax avoided. State franchise or S-corp taxes, which this calculator excludes, push the real threshold higher.",
      },
      {
        question: "Does an S corp election affect my Social Security?",
        answer:
          "Yes. Social Security benefits are based on your earnings record, and only the salary counts — distributions do not. Paying yourself a lower salary reduces the earnings on record and can lower your eventual benefit. For someone many years from retirement the effect is small relative to the annual tax saving, but it is a genuine cost rather than a free lunch.",
      },
      {
        question: "What extra paperwork does an S corp require?",
        answer:
          "Real payroll — withholding, remitting, and filing employment tax returns — plus a separate business return on Form 1120-S and a K-1 issued to yourself. Most owners use a payroll service and a preparer for the 1120-S, which is where the recurring cost comes from. The election itself is made on Form 2553, due no more than two months and 15 days after the start of the tax year it takes effect.",
      },
    ],
    sources: [IRS_SCORP, IRS_2553, IRS_SE_TAX, IRS_SCHED_C],
    toolHeading: "LLC vs S corp tax comparison",
    toolSubheading: "Both routes priced on your own profit",
    preset: {
      netProfit: 120000,
      reasonableSalary: 60000,
      filingStatus: "single",
      payrollCost: 1200,
    },
    relatedSlugs: ["s-corp-reasonable-salary-calculator"],
  },
];

// Quarterly estimated payments belong under self-employment tax, not here — the obligation comes
// from having untaxed income, not from entity choice.
export const QUARTERLY_SPOKE: SpokeEntry[] = [
  {
    calculator: "self-employment-tax",
    slug: "quarterly-estimated-tax-calculator",
    updated: "2026-09-05",
    title: "Quarterly Estimated Tax Calculator (1040-ES)",
    metaDescription:
      "Work out your quarterly estimated tax payments for 2026, plus the safe-harbor rule that switches off the underpayment penalty even if you owe more.",
    targetKeyword: "quarterly estimated tax calculator",
    estimatedVolume: 480,
    estimatedKD: 48,
    h1: "Quarterly Estimated Tax Calculator",
    introText:
      "Self-employment income arrives with no withholding, so the IRS expects you to pay as you go, in four instalments, using Form 1040-ES. Skip them and an underpayment penalty can apply even if you settle the full balance in April.\n\nOn $60,000 of net profit, a single filer owes about $12,037 in federal tax for the year — roughly $3,009 each quarter.",
    howItWorks:
      "Estimated tax covers both halves of what you owe: self-employment tax and federal income tax on your profit. The calculator above works out the annual figure and divides it into four, which is the right starting point for income that arrives evenly.\n\nThe payments are due four times a year — in April, June, and September, and again in January of the following year. The instalments are not quarters of equal length, which surprises people: the second period covers only two months. Payments are made through IRS Direct Pay, EFTPS, or with a mailed 1040-ES voucher.\n\nThe safe harbor is the part worth understanding properly, because it converts an uncertain obligation into a fixed one. You avoid the underpayment penalty if you pay at least 90% of the current year's total tax, or 100% of last year's total tax — 110% if your prior-year adjusted gross income was over $150,000. The prior-year route is the one most self-employed people should use, because last year's number is already known and this year's is a forecast. Pay the prior-year amount in four instalments and the penalty is switched off regardless of how much better the year turns out to be.\n\nIf your income is genuinely lumpy, there is a second option: the annualised income instalment method, which lets you pay in proportion to what you actually earned in each period rather than in four equal amounts. It requires more record-keeping and Form 2210 Schedule AI at filing time, but it prevents the situation where a strong fourth quarter creates a penalty for the first three.\n\nTwo practical notes. If you also have a W-2 job, increasing withholding there is often easier than making estimated payments, and withholding is treated as paid evenly across the year regardless of when it actually happened — which can retroactively fix an underpayment that estimated payments cannot. And most states with an income tax run their own estimated payment system with separate deadlines and penalties.\n\nThe reliable habit is to move a percentage of every payment into a separate account as it arrives, rather than trying to find a lump sum four times a year. Our [guide to how much to set aside](/self-employment-tax/how-much-to-set-aside-for-taxes/) works out the percentage, and the [guide to budgeting with irregular income](/guides/how-to-budget-with-irregular-income/) covers the cash-flow side.",
    commonMistakes: [
      "Assuming the payment periods are equal quarters. The second period covers only two months, so a literal quarterly rhythm misses a deadline.",
      "Estimating this year's income instead of using the prior-year safe harbor. Last year's figure is already known and switches off the penalty regardless of how this year turns out.",
      "Forgetting the 110% rule. If your prior-year AGI was over $150,000, the safe harbor is 110% of last year's tax rather than 100%.",
      "Paying the whole balance in April. The penalty is for not paying as you go, so it can apply even when you pay in full at filing.",
      "Ignoring state estimated payments. Most states with an income tax run their own system with separate deadlines and separate penalties.",
    ],
    workedExample:
      "A freelancer with $60,000 of net profit and no other income owes $8,478 of self-employment tax and $3,559 of federal income tax — $12,037 for the year, or $3,009 per instalment. Suppose their prior-year total federal tax was $9,800 and their prior-year AGI was under $150,000. Paying four instalments of $2,450 — 100% of last year's tax — switches off the underpayment penalty even though the real liability is $12,037. They will owe the $2,237 difference at filing, but without a penalty, and the certainty is usually worth more than the deferral.",
    faqs: [
      {
        question: "When are quarterly estimated taxes due?",
        answer:
          "Four times a year: in April, June, and September, and again in January of the following year. The periods are not equal quarters — the second covers only two months — so a strict three-month rhythm will miss a deadline. Payments can be made through IRS Direct Pay, EFTPS, or by mailing a Form 1040-ES voucher.",
      },
      {
        question: "What is the safe harbor rule for estimated taxes?",
        answer:
          "You avoid the underpayment penalty by paying at least 90% of the current year's tax or 100% of the prior year's total tax, rising to 110% if your prior-year adjusted gross income exceeded $150,000. The prior-year route is the practical choice for self-employed filers, because it relies on a number you already know rather than a forecast of a year still in progress.",
      },
      {
        question: "What happens if I don't pay quarterly taxes?",
        answer:
          "An underpayment penalty can apply even if you pay the full balance when you file, because the rule is about paying as you go rather than paying in total. The penalty is calculated per period, so missing early instalments costs more than missing the last one. Meeting a safe harbor removes the penalty regardless of the final balance owed.",
      },
      {
        question: "Can I pay estimated taxes through payroll withholding instead?",
        answer:
          "Yes, if you also have a W-2 job, and it is often easier. Withholding is treated as paid evenly throughout the year no matter when it actually occurred, so increasing it late in the year can retroactively cure an underpayment that estimated payments cannot. Ask your employer to adjust your Form W-4 to withhold an additional amount each pay period.",
      },
      {
        question: "What if my income varies a lot between quarters?",
        answer:
          "Use the annualised income instalment method, which lets you pay in proportion to what you actually earned in each period instead of in four equal amounts. It requires tracking income by period and completing Schedule AI of Form 2210 at filing, but it prevents a strong final quarter from creating penalties for the earlier ones. The prior-year safe harbor is the simpler alternative if you can fund it.",
      },
    ],
    sources: [IRS_ES, IRS_SE_TAX, IRS_SCHED_C],
    toolHeading: "Quarterly estimated tax",
    toolSubheading: "The quarterly figure is one quarter of the annual total",
    preset: {
      netProfit: 60000,
      filingStatus: "single",
      applyQbi: true,
    },
    relatedSlugs: ["how-much-to-set-aside-for-taxes", "1099-tax-calculator"],
  },
];
